#!/bin/bash
# SessionStart hook — orient every Claude session in the right reality before it
# touches anything (docs/LESSONS.md #6: the wrong-reality migration wasted days).
set -uo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

echo "=== Kitty session context (auto-generated by .claude/hooks/session_start.sh) ==="
echo "checkout: ${ROOT_DIR}"
echo "branch:   $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'not a git repo')"
echo "last commits:"
git log --oneline -3 2>/dev/null | sed 's/^/  /'
dirty=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
echo "uncommitted changes: ${dirty} file(s)"
if [[ -f HANDOFF.md ]]; then
  echo "--- HANDOFF.md (current state + open items — fix or explicitly defer, never re-copy) ---"
  sed -n '1,60p' HANDOFF.md
fi
echo "--- Reminders ---"
echo "* Operating protocol lives in CLAUDE.md; past failures in docs/LESSONS.md. Both are binding."
echo "* 'Done' = tests run + evidence shown. Sweep whatever your change makes stale."
