-- IL-01: image_plans.operation/anchor_job_id are added at runtime by
-- image_plans._ensure_plan_operation_columns() to handle the ALTER TABLE
-- ordering safely across fresh and existing databases, mirroring
-- 028_image_jobs_queue.sql. This migration file is intentionally a no-op;
-- it exists so schema_migrations/assert_schema_current() have a tracked
-- record of the change.
--
-- Columns added:
--   image_plans.operation        TEXT NOT NULL DEFAULT 'txt2img'
--   image_plans.anchor_job_id    TEXT
--
-- An approved plan with operation='img2img' must carry a non-null
-- anchor_job_id identifying the image being edited; /studio/generate reads
-- this column (not mutable request fields) to decide whether to call
-- image_runner.run() or image_runner.run_edit().
