-- IL ImageIntent v1 provenance.
--
-- SQLite's ALTER TABLE lacks a portable IF NOT EXISTS form for columns, so
-- gateway.image_plans._ensure_plan_intent_column() and
-- gateway.image_jobs._ensure_plan_provenance_columns() add these columns
-- idempotently at runtime for both fresh and existing databases:
--
--   image_plans.intent_json TEXT
--   image_jobs.plan_id      TEXT
--   image_jobs.intent_json  TEXT
--
-- This tracked migration intentionally contains no DDL; it makes schema
-- currency explicit without making repeated startup migrations fragile.
