"""Mount all gateway route modules on the FastAPI app."""

from __future__ import annotations

from fastapi import FastAPI

from gateway.routes import (
    actions,
    artifacts,
    ask,
    brief,
    builder_control,
    calendar,
    capture,
    chats,
    completions,
    council,
    cron,
    deadlines,
    desktop,
    dream,
    experts,
    extended,
    feedback,
    idea_mine,
    import_chatgpt,
    inbox,
    insights,
    integrations,
    journal,
    kitty_tools,
    knowledge,
    logs,
    loops,
    magic,
    memories,
    monitors,
    network,
    onboarding,
    perf,
    personality,
    projects,
    prompts,
    repairs,
    runtime,
    search,
    session_context,
    signals,
    state,
    status,
    telos,
    tutor,
    usage,
    voice,
)


def register_routes(app: FastAPI) -> None:
    for module in (
        artifacts,
        experts,
        actions,
        ask,
        brief,
        builder_control,
        calendar,
        capture,
        chats,
        completions,
        council,
        cron,
        deadlines,
        desktop,
        dream,
        feedback,
        idea_mine,
        import_chatgpt,
        inbox,
        insights,
        integrations,
        journal,
        kitty_tools,
        knowledge,
        logs,
        loops,
        memories,
        monitors,
        network,
        onboarding,
        perf,
        projects,
        prompts,
        personality,
        repairs,
        runtime,
        search,
        session_context,
        signals,
        state,
        status,
        telos,
        tutor,
        usage,
        voice,
    extended,
    magic,
):
        app.include_router(module.router)
