#!/usr/bin/env python3
"""docs_system_map.py — Generate SYSTEM_MAP.md from document frontmatter.

Parses the governed documentation corpus for YAML frontmatter and produces a
structured markdown map showing each document's title, type, status, and
relationship links. Supports --check mode to verify the map is current.
"""

import sys
from datetime import datetime
from pathlib import Path

try:
    from scripts.docs_lint import collect_docs, read_frontmatter
except ModuleNotFoundError:  # Direct script execution adds scripts/ to sys.path.
    from docs_lint import collect_docs, read_frontmatter

OUTPUT_FILE = "docs/SYSTEM_MAP.md"


def build_map():
    docs_root = Path(__file__).parent.parent / "docs"
    docs = collect_docs(docs_root)
    lines = []
    lines.append("<!-- Generated by scripts/docs_system_map.py — DO NOT EDIT MANUALLY -->")
    lines.append("# Kitty Documentation System Map\n")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Documents:** {len(docs)}\n")

    current_dir = ""
    for doc in docs:
        rel = doc.relative_to(docs_root)
        parent = str(rel.parent) if str(rel.parent) != "." else ""
        if parent != current_dir:
            current_dir = parent
            if current_dir:
                lines.append(f"\n## {current_dir}/\n")
            else:
                lines.append("\n## Root\n")

        fm = read_frontmatter(doc)
        if fm:
            title = fm.get("title", rel.stem)
            doc_type = fm.get("type", "unknown")
            status = fm.get("status", "unknown")
            derives = fm.get("derives_from", [])

            status_icon = {"canonical": "[C]", "draft": "[D]", "deprecated": "[X]", "superseded": "[S]"}.get(status, "[?]")
            lines.append(f"- {status_icon} **{title}** `[{rel}]` _({doc_type})_")
            if derives:
                lines.append(f"  - derives from: {', '.join(f'`{d}`' for d in derives)}")
        else:
            lines.append(f"- [?] **{rel.stem}** `[{rel}]` _(no frontmatter)_")

    return "\n".join(lines) + "\n"


def main():
    docs_root = Path(__file__).parent.parent
    output_path = docs_root / OUTPUT_FILE
    content = build_map()

    if "--check" in sys.argv:
        if not output_path.exists():
            print("SYSTEM_MAP.md does not exist. Run: python3 scripts/docs_system_map.py")
            sys.exit(1)
        existing = output_path.read_text()
        # Strip the generated timestamp line for comparison
        existing_lines = existing.split("\n")
        new_lines = content.split("\n")
        # Compare everything except the timestamp line
        existing_cmp = [
            line for line in existing_lines if not line.startswith("**Generated:**")
        ]
        new_cmp = [line for line in new_lines if not line.startswith("**Generated:**")]
        if existing_cmp == new_cmp:
            print("SYSTEM_MAP.md is current.")
            sys.exit(0)
        else:
            print("SYSTEM_MAP.md is stale. Run: python3 scripts/docs_system_map.py")
            sys.exit(1)
    else:
        output_path.write_text(content)
        print(f"Generated {output_path} ({len(collect_docs(docs_root / 'docs'))} documents)")


if __name__ == "__main__":
    main()
