#!/usr/bin/env python3
"""docs_system_map.py — Generate SYSTEM_MAP.md from document frontmatter.

Parses all .md files under docs/ for YAML frontmatter and produces a
structured markdown map showing each document's title, type, status, and
relationship links. Supports --check mode to verify the map is current.
"""

import os
import sys
from pathlib import Path
import yaml
from datetime import datetime

SKIP_DIRS = {"codemap", "archive", "retired", ".DS_Store", "examples", "evidence", "fable-context", "initiatives", "packets"}
OUTPUT_FILE = "docs/SYSTEM_MAP.md"


def read_frontmatter(path: Path):
    with open(path) as f:
        content = f.read()
    if not content.startswith("---"):
        return None
    end = content.find("---", 3)
    if end == -1:
        return None
    try:
        return yaml.safe_load(content[3:end]) or {}
    except yaml.YAMLError:
        return None


def collect_docs(root: Path):
    result = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")]
        for fname in sorted(filenames):
            if fname.endswith(".md"):
                result.append(Path(dirpath) / fname)
    return result


def build_map():
    docs_root = Path(__file__).parent.parent / "docs"
    docs = collect_docs(docs_root)
    lines = []
    lines.append("<!-- Generated by scripts/docs_system_map.py — DO NOT EDIT MANUALLY -->")
    lines.append(f"# Kitty Documentation System Map\n")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Documents:** {len(docs)}\n")

    current_dir = ""
    for doc in docs:
        rel = doc.relative_to(docs_root)
        parent = str(rel.parent) if str(rel.parent) != "." else ""
        if parent != current_dir:
            current_dir = parent
            if current_dir:
                lines.append(f"\n## {current_dir}/\n")
            else:
                lines.append(f"\n## Root\n")

        fm = read_frontmatter(doc)
        if fm:
            title = fm.get("title", rel.stem)
            doc_type = fm.get("type", "unknown")
            status = fm.get("status", "unknown")
            derives = fm.get("derives_from", [])
            implements = fm.get("implements", [])
            refs = fm.get("referenced_by", [])
            supersedes = fm.get("supersedes", [])
            superseded_by = fm.get("superseded_by", [])

            status_icon = {"canonical": "[C]", "draft": "[D]", "deprecated": "[X]", "superseded": "[S]"}.get(status, "[?]")
            lines.append(f"- {status_icon} **{title}** `[{rel}]` _({doc_type})_")
            if derives:
                lines.append(f"  - derives from: {', '.join(f'`{d}`' for d in derives)}")
        else:
            lines.append(f"- [?] **{rel.stem}** `[{rel}]` _(no frontmatter)_")

    return "\n".join(lines) + "\n"


def main():
    docs_root = Path(__file__).parent.parent
    output_path = docs_root / OUTPUT_FILE
    content = build_map()

    if "--check" in sys.argv:
        if not output_path.exists():
            print("SYSTEM_MAP.md does not exist. Run: python3 scripts/docs_system_map.py")
            sys.exit(1)
        existing = output_path.read_text()
        # Strip the generated timestamp line for comparison
        existing_lines = existing.split("\n")
        new_lines = content.split("\n")
        # Compare everything except the timestamp line
        existing_cmp = [l for l in existing_lines if not l.startswith("**Generated:**")]
        new_cmp = [l for l in new_lines if not l.startswith("**Generated:**")]
        if existing_cmp == new_cmp:
            print("SYSTEM_MAP.md is current.")
            sys.exit(0)
        else:
            print("SYSTEM_MAP.md is stale. Run: python3 scripts/docs_system_map.py")
            sys.exit(1)
    else:
        output_path.write_text(content)
        print(f"Generated {output_path} ({len(collect_docs(docs_root / 'docs'))} documents)")


if __name__ == "__main__":
    main()
